# Travis CI
dist: xenial
language: python

python:
  - "3.6"

cache:
  - pip

install:
  - pip install -r scripts/requirements.txt
  - pip install -r scripts/dev_requirements.txt
  - python setup.py develop

services:
  - redis-server

script:
  - pushd demo
  - pytest demo --cov=demo --cov=django_taskflow --cov-report term-missing
  - pylint demo --rcfile=../pylintrc
  - popd
  - pylint django_taskflow

after_success:
  - coveralls
